package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_studio/editor"
)

func Generate(proj *editor.Project, outputPath string) error {
	// Create output directory
	if err := os.MkdirAll(outputPath, 0755); err != nil {
		return err
	}

	// Create go.mod
	goMod := `module github.com/user/` + proj.Name + `

go 1.24

require github.com/ibilalkhan1/fyp_pixelforge v0.0.0

replace github.com/ibilalkhan1/fyp_pixelforge => /home/tux/Pictures/basheer-go
`
	if err := os.WriteFile(filepath.Join(outputPath, "go.mod"), []byte(goMod), 0644); err != nil {
		return err
	}

	// Generate main.go
	mainGo := generateMain(proj)
	if err := os.WriteFile(filepath.Join(outputPath, "main.go"), []byte(mainGo), 0644); err != nil {
		return err
	}

	// Copy sprite assets
	for _, sprite := range proj.Sprites {
		destPath := filepath.Join(outputPath, "assets", "sprites")
		os.MkdirAll(destPath, 0755)
		srcData, err := os.ReadFile(sprite.Path)
		if err == nil {
			os.WriteFile(filepath.Join(destPath, filepath.Base(sprite.Path)), srcData, 0644)
		}
	}

	// Copy audio assets
	for _, audio := range proj.AudioFiles {
		destPath := filepath.Join(outputPath, "assets", "audio")
		os.MkdirAll(destPath, 0755)
		srcData, err := os.ReadFile(audio.Path)
		if err == nil {
			os.WriteFile(filepath.Join(destPath, filepath.Base(audio.Path)), srcData, 0644)
		}
	}

	return nil
}

func generateMain(proj *editor.Project) string {
	var sb strings.Builder

	sb.WriteString(`// Auto-generated by Pixelforge Studio
package main

import (
	_ "embed"
	"fmt"

	"github.com/ibilalkhan1/fyp_pixelforge"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_ebiten"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_key"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_pad"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_mouse"
)

`)

	// Embed sprites
	if len(proj.Sprites) > 0 {
		sb.WriteString("//go:embed assets/sprites/*.png\n")
		sb.WriteString("var assetsSprites []byte\n\n")
	}

	// Generate sprite variables
	for _, sprite := range proj.Sprites {
		name := strings.ReplaceAll(sprite.Name, " ", "")
		sb.WriteString(fmt.Sprintf("var sprite%s pixelforge.Sprite\n", name))
	}
	sb.WriteString("\n")

	// Generate init function
	sb.WriteString("func init() {\n")
	sb.WriteString(fmt.Sprintf("	pixelforge.SetScreenSize(%d, %d)\n", proj.ScreenWidth, proj.ScreenHeight))
	sb.WriteString(fmt.Sprintf("	pixelforge.SetTPS(%d)\n", proj.TPS))

	if len(proj.Sprites) > 0 {
		sb.WriteString("\n	// Load sprites\n")
		sb.WriteString("	sprites := pixelforge.DecodeCanvas(assetsSprites)\n")
		for i, sprite := range proj.Sprites {
			name := strings.ReplaceAll(sprite.Name, " ", "")
			sb.WriteString(fmt.Sprintf("	sprite%s = pixelforge.SpriteFrom(sprites, %d, %d, %d, %d)\n",
				name, i*sprite.FrameW, 0, sprite.FrameW, sprite.FrameH))
		}
	}

	sb.WriteString("}\n\n")

	// Add user Update code
	sb.WriteString(proj.UpdateCode)
	sb.WriteString("\n\n")

	// Add user Draw code
	sb.WriteString(proj.DrawCode)
	sb.WriteString("\n\n")

	// Main function
	sb.WriteString(`func main() {
	pixelforge.Update = update
	pixelforge.Draw = draw
	pixelforge_ebiten.Run()
}
`)

	return sb.String()
}
