package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_studio/editor"
)

func GenerateFromState(state *editor.EditorState, outputPath, gameName string) error {
	os.MkdirAll(outputPath, 0755)
	os.MkdirAll(filepath.Join(outputPath, "assets", "sprites"), 0755)

	// go.mod
	goMod := fmt.Sprintf(`module github.com/user/%s

go 1.24

require github.com/ibilalkhan1/fyp_pixelforge v0.0.0

replace github.com/ibilalkhan1/fyp_pixelforge => %s
`, gameName, "/home/tux/Pictures/basheer-go")
	os.WriteFile(filepath.Join(outputPath, "go.mod"), []byte(goMod), 0644)

	// main.go
	main := generateMainFromState(state, gameName)
	os.WriteFile(filepath.Join(outputPath, "main.go"), []byte(main), 0644)

	// Copy sprites
	for _, sprite := range state.Sprites {
		if sprite.Path != "" {
			data, err := os.ReadFile(sprite.Path)
			if err == nil {
				os.WriteFile(filepath.Join(outputPath, "assets", "sprites", filepath.Base(sprite.Path)), data, 0644)
			}
		}
	}

	return nil
}

func generateMainFromState(state *editor.EditorState, gameName string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`// %s - Generated by Pixelforge Studio
package main

import (
	"os"

	"github.com/ibilalkhan1/fyp_pixelforge"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_ebiten"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_key"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_pad"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_mouse"
)

`, gameName))

	// Scene objects
	sb.WriteString("// Scene objects\n")
	sb.WriteString("type SceneObject struct {\n")
	sb.WriteString("\tID       int\n")
	sb.WriteString("\tSpriteName string\n")
	sb.WriteString("\tX, Y     int\n")
	sb.WriteString("\tWidth, Height int\n")
	sb.WriteString("}\n\n")

	sb.WriteString("var sceneObjects = []SceneObject{\n")
	for _, obj := range state.SceneObjects {
		sb.WriteString(fmt.Sprintf("\t{%d, \"%s\", %d, %d, %d, %d},\n",
			obj.ID, obj.SpriteName, obj.X, obj.Y, obj.Width, obj.Height))
	}
	sb.WriteString("}\n\n")

	// GetSprite helper
	sb.WriteString(`func getSprite(name string) pixelforge.Sprite {
	// This would be generated based on loaded sprites
	return nil
}
`)

	// init
	sb.WriteString("func init() {\n")
	sb.WriteString(fmt.Sprintf("\tpixelforge.SetScreenSize(%d, %d)\n", state.ScreenWidth, state.ScreenHeight))
	sb.WriteString(fmt.Sprintf("\tpixelforge.SetTPS(%d)\n", state.TPS))
	sb.WriteString("}\n\n")

	// Update
	sb.WriteString(state.UpdateCode)
	sb.WriteString("\n\n")

	// Draw
	sb.WriteString(state.DrawCode)
	sb.WriteString("\n\n")

	// main
	sb.WriteString(`func main() {
	pixelforge.Update = update
	pixelforge.Draw = draw
	pixelforge_ebiten.Run()
}
`)

	return sb.String()
}
