package codegen

// All Go source templates the generator emits. Kept in one file so a
// reviewer can see every byte that ends up in user-facing exported
// games. Templates are deliberately minimal — the runtime loads the
// embedded .pforge for every value-bearing decision.

// mainGoTemplate emits a thin Ebitengine host that loads the embedded
// project and surrenders control to pixelforge_ebiten.Run. The file is
// gofmt'd before it lands on disk, so the indentation here is
// indicative only.
// mainGoTemplate is idea #7 v1 U1's thin shell. The actual engine
// wiring lives in the generated capsule.go (see capsuleGoTemplate);
// main.go's only job is to surrender control to CapsuleRun.
// Both files share package main so the //go:embed directives in
// capsule.go resolve against project.pforge + assets/ in outDir.
const mainGoTemplate = `// Code generated by pixelforge_studio/codegen. DO NOT EDIT.
//
// Generator template version: {{.TemplateVersion}}.
// Source project name: {{.ProjectName}}.
package main

import "log"

func main() {
	if err := CapsuleRun(CapsuleDefaults()); err != nil {
		log.Fatalf("pixelforge: capsule run: %v", err)
	}
}
`

// capsuleGoTemplate is idea #7 v1 U1's Capsule wrapper — the seam
// where every prior plan's runtime contract converges. Embeds the
// project + assets, exposes Run + Defaults + Assets + ProjectData,
// and stamps typed constants for scenes + items so downstream code
// references them safely.
const capsuleGoTemplate = `// Code generated by pixelforge_studio/codegen. DO NOT EDIT.
//
// Generator template version: {{.TemplateVersion}}.
// Source project name: {{.ProjectName}}.
package main

import (
	"bytes"
	"embed"
	_ "embed"
	"fmt"

	"github.com/ibilalkhan1/fyp_pixelforge"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_ebiten"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_project"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_studio/capsuleruntime"
)

//go:embed project.pforge
var capsuleProjectData []byte

//go:embed all:assets
var capsuleAssetsFS embed.FS

// CapsuleOpts tunes CapsuleRun's behaviour. DataOverride lets
// the editor preview pass its in-memory project state (unsaved
// edits) through the same code path the shipped binary uses —
// one Capsule contract, multiple call sites per origin R2.
type CapsuleOpts struct {
	WindowWidth  int
	WindowHeight int
	Fullscreen   bool
	DebugOverlay bool
	DataOverride *pixelforge_project.Project
}

// CapsuleDefaults returns sensible CapsuleOpts for the shipped binary.
func CapsuleDefaults() CapsuleOpts { return CapsuleOpts{} }

// CapsuleRun is the foundational runtime sequence the Capsule
// executes. Loads the project (override or embedded), applies
// engine globals, then surrenders to pixelforge_ebiten.Run.
func CapsuleRun(opts CapsuleOpts) error {
	p := opts.DataOverride
	if p == nil {
		var err error
		p, err = pixelforge_project.LoadReader(bytes.NewReader(capsuleProjectData))
		if err != nil {
			return fmt.Errorf("capsule: load embedded project: %w", err)
		}
	}
	if p.ScreenWidth > 0 && p.ScreenHeight > 0 {
		pixelforge.SetScreenSize(p.ScreenWidth, p.ScreenHeight)
	}
	if p.TPS > 0 {
		pixelforge.SetTPS(p.TPS)
	}
	// Boot decodes every sprite/audio/dialogue asset out of the
	// embedded FS into the runtime registries entity render +
	// verb-recipe subscribers consume, then installs the
	// "verbs.bus" topic handlers. The capsule never reaches Run
	// without populated registries — partial state would silently
	// drop authored verbs at runtime.
	if _, err := capsuleruntime.Boot(p, capsuleAssetsFS, capsuleruntime.Options{}); err != nil {
		return fmt.Errorf("capsule: boot runtime: %w", err)
	}
	pixelforge_ebiten.Run()
	return nil
}

// CapsuleAssets returns the embedded asset FS so callers can
// read sprite/audio bytes without coupling to the embed directive.
func CapsuleAssets() embed.FS { return capsuleAssetsFS }

// CapsuleProjectData returns a copy of the raw project.pforge
// bytes so callers can parse the schema directly without going
// through CapsuleRun.
func CapsuleProjectData() []byte {
	out := make([]byte, len(capsuleProjectData))
	copy(out, capsuleProjectData)
	return out
}

// capsuleCredits is the CC-BY attribution data assetlibrary.
// AssembleCredits collected at codegen time. Empty when the
// project uses only CC0 assets (or no library packs at all);
// non-empty triggers the engine menu's auto-injected "Credits"
// entry and the WASM bundler's "View Credits" splash button.
var capsuleCredits = []capsuleruntime.CreditEntry{
{{- range .Credits}}
	{Name: {{printf "%q" .Name}}, License: {{printf "%q" .License}}, Author: {{printf "%q" .Author}}, SourceURL: {{printf "%q" .SourceURL}}},
{{- end}}
}

// CapsuleCredits returns a copy of the embedded credits dataset
// so callers (menu renderer, WASM bundler) read a stable slice.
func CapsuleCredits() []capsuleruntime.CreditEntry {
	out := make([]capsuleruntime.CreditEntry, len(capsuleCredits))
	copy(out, capsuleCredits)
	return out
}

func init() {
	// Publish the embedded credits to the capsuleruntime registry
	// so the engine menu system + diagnostics see them without
	// re-reading the literal.
	capsuleruntime.RegisterCredits(capsuleCredits)
}

{{range .SceneIDs}}// SceneID{{.Camel}} names scene {{printf "%q" .Raw}}.
const SceneID{{.Camel}} = {{printf "%q" .Raw}}

{{end -}}
{{range .ItemIDs}}// ItemID{{.Camel}} names item {{printf "%q" .Raw}}.
const ItemID{{.Camel}} = {{printf "%q" .Raw}}

{{end -}}
`

// goModTemplate emits the exported game's go.mod. The strategy
// determines whether it carries a vendor snapshot, a published
// version pin, or a local replace directive.
const goModTemplate = `// Code generated by pixelforge_studio/codegen. DO NOT EDIT.

module {{.ModulePath}}

go 1.24

require github.com/ibilalkhan1/fyp_pixelforge {{.EngineRequireVersion}}
{{if .EngineReplacePath}}
replace github.com/ibilalkhan1/fyp_pixelforge => {{.EngineReplacePath}}
{{end}}
`
