package codegen

// All Go source templates the generator emits. Kept in one file so a
// reviewer can see every byte that ends up in user-facing exported
// games. Templates are deliberately minimal — the runtime loads the
// embedded .pforge for every value-bearing decision.

// mainGoTemplate emits a thin Ebitengine host that loads the embedded
// project and surrenders control to pixelforge_ebiten.Run. The file is
// gofmt'd before it lands on disk, so the indentation here is
// indicative only.
const mainGoTemplate = `// Code generated by pixelforge_studio/codegen. DO NOT EDIT.
//
// Generator template version: {{.TemplateVersion}}.
// Source project name: {{.ProjectName}}.
package main

import (
	"bytes"
	_ "embed"
	"log"

	"github.com/ibilalkhan1/fyp_pixelforge"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_ebiten"
	"github.com/ibilalkhan1/fyp_pixelforge/pixelforge_project"
)

//go:embed project.pforge
var projectData []byte

func main() {
	p, err := pixelforge_project.LoadReader(bytes.NewReader(projectData))
	if err != nil {
		log.Fatalf("pixelforge: load embedded project: %v", err)
	}
	applyProject(p)
	pixelforge_ebiten.Run()
}

// applyProject pushes the loaded schema into the engine. M1 wires only
// the surface needed to run an empty project: screen size + TPS. Later
// milestones populate sprites, scenes, audio, and behaviors here.
func applyProject(p *pixelforge_project.Project) {
	if p.ScreenWidth > 0 && p.ScreenHeight > 0 {
		pixelforge.SetScreenSize(p.ScreenWidth, p.ScreenHeight)
	}
	if p.TPS > 0 {
		pixelforge.SetTPS(p.TPS)
	}
}
`

// goModTemplate emits the exported game's go.mod. The strategy
// determines whether it carries a vendor snapshot, a published
// version pin, or a local replace directive.
const goModTemplate = `// Code generated by pixelforge_studio/codegen. DO NOT EDIT.

module {{.ModulePath}}

go 1.24

require github.com/ibilalkhan1/fyp_pixelforge {{.EngineRequireVersion}}
{{if .EngineReplacePath}}
replace github.com/ibilalkhan1/fyp_pixelforge => {{.EngineReplacePath}}
{{end}}
`
