package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestSplitLegToken_ExplicitLabel asserts "label=path" splits as
// expected.
func TestSplitLegToken_ExplicitLabel(t *testing.T) {
	label, path := splitLegToken("macos-arm64=/tmp/x.json")
	assert.Equal(t, "macos-arm64", label)
	assert.Equal(t, "/tmp/x.json", path)
}

// TestSplitLegToken_DerivedFromFilename asserts the filename-deriving
// fallback strips both ".json" + the "test-results-" prefix.
func TestSplitLegToken_DerivedFromFilename(t *testing.T) {
	label, path := splitLegToken("dir/test-results-linux-amd64.json")
	assert.Equal(t, "linux-amd64", label)
	assert.Equal(t, "dir/test-results-linux-amd64.json", path)
}

// TestSplitLegToken_BareFilename keeps a bare filename as the label
// when "test-results-" is absent.
func TestSplitLegToken_BareFilename(t *testing.T) {
	label, _ := splitLegToken("/tmp/runner.json")
	assert.Equal(t, "runner", label)
}

// TestLoadLegs_ParsesAllTokens drops two synthetic JSON files into a
// tempdir + asserts both legs surface in the result.
func TestLoadLegs_ParsesAllTokens(t *testing.T) {
	dir := t.TempDir()
	linuxPath := filepath.Join(dir, "test-results-linux-amd64.json")
	macosPath := filepath.Join(dir, "test-results-macos-arm64.json")

	require.NoError(t, os.WriteFile(linuxPath, []byte(`{"Action":"pass","Package":"x/asteroids_proof","Test":"TestAsteroidsProof"}`+"\n"), 0o644))
	require.NoError(t, os.WriteFile(macosPath, []byte(`{"Action":"fail","Package":"x/asteroids_proof","Test":"TestAsteroidsProof"}`+"\n"), 0o644))

	legs, err := loadLegs(linuxPath + "," + macosPath)
	require.NoError(t, err)
	require.Len(t, legs, 2)
	assert.Equal(t, "linux-amd64", legs[0].Label)
	assert.Equal(t, "macos-arm64", legs[1].Label)
}

// TestLoadLegs_RejectsEmptySpec ensures the loader returns an error
// when -in is the empty string after stripping whitespace.
func TestLoadLegs_RejectsEmptySpec(t *testing.T) {
	_, err := loadLegs(" , , ")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "no usable legs")
}

// TestWriteOutput_AtomicRename writes a matrix file + asserts the
// renamed result contains the expected headline. Also asserts no
// leftover ".capability-matrix-*.md.tmp" siblings remain in the dir.
func TestWriteOutput_AtomicRename(t *testing.T) {
	dir := t.TempDir()
	resultsPath := filepath.Join(dir, "results.json")
	require.NoError(t, os.WriteFile(resultsPath,
		[]byte(`{"Action":"pass","Package":"x/asteroids_proof","Test":"TestAsteroidsProof"}`+"\n"),
		0o644))

	legs, err := loadLegs(resultsPath)
	require.NoError(t, err)

	outPath := filepath.Join(dir, "matrix.md")
	require.NoError(t, writeOutput(outPath, legs))

	data, err := os.ReadFile(outPath) //nolint:gosec // test reads file it just wrote
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(data), "<!-- Generated by"),
		"output file should lead with the do-not-edit comment")

	entries, err := os.ReadDir(dir)
	require.NoError(t, err)
	for _, e := range entries {
		assert.False(t, strings.HasSuffix(e.Name(), ".tmp"),
			"no .tmp siblings should remain after successful rename: %s", e.Name())
	}
}
