package catalog

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// WriteVerbCatalogMarkdown emits the human-readable verb catalog to w.
// Output is grouped by VerbKind (Action recipes, then Condition
// recipes) and sorted by name within each group, so two consecutive
// invocations produce byte-identical output. The cmd/gendocs binary +
// the docgen unit tests both call this function.
//
// The output shape mirrors the one documented in U24 of plan
// docs/plans/2026-05-19-001-feat-arcade-shipping-v2-plan.md.
func WriteVerbCatalogMarkdown(w io.Writer) error {
	verbs := ListVerbs()

	// Partition by kind. ListVerbs already returns name-sorted, so
	// the partitions inherit that ordering.
	var actions, conditions []VerbInfo
	for _, v := range verbs {
		if v.Kind == VerbKindCondition {
			conditions = append(conditions, v)
		} else {
			actions = append(actions, v)
		}
	}

	bw := &writeErr{w: w}
	bw.WriteString("# Pixelforge Verb Catalog\n\n")
	bw.WriteString("Generated by `go generate ./pixelforge_studio/scripting/catalog/...`.\n")
	bw.WriteString("Do not edit by hand — regenerate after registry changes.\n\n")
	bw.WriteString(fmt.Sprintf("Catalog size: **%d** verb recipes (%d action, %d condition).\n\n",
		len(verbs), len(actions), len(conditions)))

	if len(actions) > 0 {
		bw.WriteString("## Action recipes\n\n")
		for _, v := range actions {
			writeVerbSection(bw, v)
		}
	}
	if len(conditions) > 0 {
		bw.WriteString("## Condition recipes\n\n")
		for _, v := range conditions {
			writeVerbSection(bw, v)
		}
	}

	// Step Kinds (the routine-step builders) round out the
	// catalog. They are not Recipes — they ship from
	// builtin_steps.go via RegisterStep — but ship in the doc so
	// designers see the full surface in one place.
	steps := AllSteps()
	if len(steps) > 0 {
		sort.Strings(steps)
		bw.WriteString("## Step kinds\n\n")
		bw.WriteString("Step kinds are routine primitives consumed by the step-lane authoring path.\n")
		bw.WriteString("They are not verb recipes; they appear here so designers can see the full catalog surface.\n\n")
		for _, s := range steps {
			bw.WriteString(fmt.Sprintf("- `%s`\n", s))
		}
		bw.WriteString("\n")
	}

	return bw.err
}

// writeVerbSection emits a single verb's section. Stable ordering is
// enforced by the caller — VerbInfo is already arg-sorted from
// recipeToVerbInfo.
func writeVerbSection(bw *writeErr, v VerbInfo) {
	bw.WriteString(fmt.Sprintf("### `%s`\n\n", v.Name))

	if v.Kind == VerbKindCondition {
		bw.WriteString(fmt.Sprintf("**Condition kind:** `%s`\n\n", v.ConditionKind))
	} else {
		bw.WriteString(fmt.Sprintf("**Action kind:** `%s`\n\n", v.ActionKind))
	}
	if v.Topic != "" {
		bw.WriteString(fmt.Sprintf("**Topic:** `%s`\n\n", v.Topic))
	}

	if len(v.Args) > 0 {
		bw.WriteString("**Arguments:**\n\n")
		for _, a := range v.Args {
			bw.WriteString(fmt.Sprintf("- `%s` (%s) — default: %s\n",
				a.Name, a.Type, formatDefault(a.Default)))
		}
		bw.WriteString("\n")
	}

	if len(v.RelevantTriggers) > 0 {
		// Copy then sort for stable output. Triggers in the recipe
		// definition are author-ordered (logical groupings); the
		// doc surface lists them alphabetically.
		trig := append([]string(nil), v.RelevantTriggers...)
		sort.Strings(trig)
		bw.WriteString("**Relevant triggers:** ")
		for i, t := range trig {
			if i > 0 {
				bw.WriteString(", ")
			}
			bw.WriteString(fmt.Sprintf("`%s`", t))
		}
		bw.WriteString("\n\n")
	}
}

// formatDefault returns a stable string rendering of a default value.
// Numbers print without trailing-zero noise; strings are double-quoted
// (matching Go's %q); booleans print as "true"/"false"; nil prints as
// "(none)".
func formatDefault(v any) string {
	switch x := v.(type) {
	case nil:
		return "(none)"
	case string:
		if x == "" {
			return `""`
		}
		return fmt.Sprintf("%q", x)
	case bool:
		if x {
			return "true"
		}
		return "false"
	case float64:
		return trimFloat(x)
	case float32:
		return trimFloat(float64(x))
	case int:
		return fmt.Sprintf("%d", x)
	case int32:
		return fmt.Sprintf("%d", x)
	case int64:
		return fmt.Sprintf("%d", x)
	default:
		return fmt.Sprintf("%v", x)
	}
}

// trimFloat renders f without the trailing ".000..." noise that
// strconv.FormatFloat('g'/'e') varies by exponent. Whole numbers
// render as their integer form ("5"), fractional numbers keep enough
// precision to round-trip the JSON-source default ("0.3", "0.2").
func trimFloat(f float64) string {
	// Whole numbers render as integers — "5", not "5.000".
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	s := fmt.Sprintf("%.6f", f)
	// Strip trailing zeros after the decimal point so "0.300000"
	// becomes "0.3" — matches how the catalog author wrote them.
	s = strings.TrimRight(s, "0")
	s = strings.TrimRight(s, ".")
	return s
}

// writeErr wraps an io.Writer with sticky-error semantics so the doc
// emitter can call WriteString many times without checking every
// return. The first error wins; subsequent writes no-op.
type writeErr struct {
	w   io.Writer
	err error
}

func (b *writeErr) WriteString(s string) {
	if b.err != nil {
		return
	}
	_, b.err = io.WriteString(b.w, s)
}
